<a href="https://colab.research.google.com/github/RahulSinghPundir/Decision-Tree-Classifier/blob/main/Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [218]:
# Importing the basic modules.
import numpy as np
import pandas as pd

In [219]:
# Downloading the dataset if not downloaded.
# !wget -O drug200.csv https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/drug200.csv

In [220]:
# Reading the dataset and taking an overlook of it for knowing the important features.
df=pd.read_csv("drug200.csv", delimiter=",")
df.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

In [221]:
# This X(numpy.ndarray) is storig the independent variables.
X=df.iloc[:,:5].values
print(X[:5])



[[23 'F' 'HIGH' 'HIGH' 25.355]
 [47 'M' 'LOW' 'HIGH' 13.093]
 [47 'M' 'LOW' 'HIGH' 10.114]
 [28 'F' 'NORMAL' 'HIGH' 7.798]
 [61 'F' 'LOW' 'HIGH' 18.043]]


In [222]:
# This Y(numpy.ndarray) is storing the dependent variable/output.
Y=df.iloc[:,5:].values
print(Y[:5])

[['drugY']
 ['drugC']
 ['drugC']
 ['drugX']
 ['drugY']]


In [223]:
''' Importing the Label Encoder for encoding some features which have string datatype
 like sex,cholesterol,Blood Pressure to give them a specific number to apply in model.''' 
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()

# Fitting labelencoder for sex feature which give a value of 0 to Female and 1 to Male.
label.fit(['F','M'])

# Changing our sex feature in dataset to the 0's and 1's.
X[:,1] = label.transform(X[:,1]) 

# Look at the 2 column it is converted into 0's and 1's
X[:5]



array([[23, 0, 'HIGH', 'HIGH', 25.355],
       [47, 1, 'LOW', 'HIGH', 13.093],
       [47, 1, 'LOW', 'HIGH', 10.114],
       [28, 0, 'NORMAL', 'HIGH', 7.798],
       [61, 0, 'LOW', 'HIGH', 18.043]], dtype=object)

In [224]:
# Fitting labelencoder for Blood pressure feature which give a value of 0 to High and 1 to Low and 2 to Normal.
label.fit(['HIGH','LOW','NORMAL'])
# Changing our sex feature in dataset to the 0's, 1's and 2.
X[:,2]=label.transform(X[:,2])
# Look at the 3 column it is converted into 0's, 1's and 2.
X[:5]

array([[23, 0, 0, 'HIGH', 25.355],
       [47, 1, 1, 'HIGH', 13.093],
       [47, 1, 1, 'HIGH', 10.114],
       [28, 0, 2, 'HIGH', 7.798],
       [61, 0, 1, 'HIGH', 18.043]], dtype=object)

In [225]:
# Doing the same thing for cholesterol but in this no need to fit it as label encoder is already fit for same(High,Low,Normal).
X[:,3]=label.transform(X[:,3])
X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.114],
       [28, 0, 2, 0, 7.798],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [226]:
# Analysing the number of outcomes/drugs from dataset.
print(df['Drug'].value_counts())

drugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64


In [227]:
# Splitting the dataset in traning and testing 80% for training and 20% for testing.
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,train_size=0.8,random_state=4)

# Verify the shape that train and test split work correctly or not. 
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(160, 5) (40, 5) (160, 1) (40, 1)


In [228]:
# Importing the decision treee classifier from sklearn package 
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(criterion='entropy')

# Training the model for traing set.
tree.fit(x_train,y_train)

# Predicting the y_test for x_test.
yhat=tree.predict(x_test)

In [229]:
# From accuracy score we can accuracy of our model.
from sklearn.metrics import accuracy_score
print("Accuracy is on training set is : ",accuracy_score(y_train,tree.predict(x_train)))
print("Accuracy is on test set is : ",accuracy_score(y_test,yhat))

Accuracy is on training set is :  1.0
Accuracy is on test set is :  0.95
